#!/bin/bash
sqlname=$(sed -n "/define('DB_NAME', '/s/.*, '\([^']*\).*/\1/p" $1)
sqluser=$(sed -n "/define('DB_USER', '/s/.*, '\([^']*\).*/\1/p" $1)
sqlpass=$(sed -n "/define('DB_PASSWORD', '/s/.*, '\([^']*\).*/\1/p" $1)
sqlhost=$(sed -n "/define('DB_HOST', '/s/.*, '\([^']*\).*/\1/p" $1)

mysqldump --host=$sqlhost --user=$sqluser -p$sqlpass --skip-lock-tables $sqlname | gzip -9 > $sqlname.sql.gz