#!/bin/bash
sqlname=$(sed -n "/define('DB_NAME', '/s/.*, '\([^']*\).*/\1/p" $1)
sqluser=$(sed -n "/define('DB_USER', '/s/.*, '\([^']*\).*/\1/p" $1)
sqlpass=$(sed -n "/define('DB_PASSWORD', '/s/.*, '\([^']*\).*/\1/p" $1)
sqlhost=$(sed -n "/define('DB_HOST', '/s/.*, '\([^']*\).*/\1/p" $1)

mysql -h $sqlhost -u $sqluser -p$sqlpass $sqlname
